import type { CardioGeraet, Exercise, StretchExercise } from './types'

// 20 gängige Gym-Maschinenübungen mit Muskelzuordnung (Abschnitt 6, Phase 1).
// Die antagonistGruppe verknüpft die Paare für die Ratio-Analyse aus Abschnitt 5.2.
export const KRAFT_UEBUNGEN: Exercise[] = [
  {
    id: 'brustpresse',
    name: 'Brustpresse',
    maschine: 'Chest Press',
    primaerMuskeln: ['brust'],
    sekundaerMuskeln: ['trizeps', 'vordere_schulter'],
    bewegungsTyp: 'push',
    antagonistGruppe: 'druck_horizontal',
    illustrationId: 'brustpresse',
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    maschine: 'Pec Deck',
    primaerMuskeln: ['brust'],
    sekundaerMuskeln: ['vordere_schulter'],
    bewegungsTyp: 'push',
    illustrationId: 'butterfly',
  },
  {
    id: 'schulterpresse',
    name: 'Schulterpresse',
    maschine: 'Shoulder Press',
    primaerMuskeln: ['seitliche_schulter', 'vordere_schulter'],
    sekundaerMuskeln: ['trizeps'],
    bewegungsTyp: 'push',
    antagonistGruppe: 'druck_vertikal',
    illustrationId: 'schulterpresse',
  },
  {
    id: 'seitheben',
    name: 'Seitheben',
    maschine: 'Lateral Raise Machine',
    primaerMuskeln: ['seitliche_schulter'],
    sekundaerMuskeln: ['nacken_trapez'],
    bewegungsTyp: 'push',
    illustrationId: 'seitheben',
  },
  {
    id: 'trizepsdruecken',
    name: 'Trizepsdrücken',
    maschine: 'Triceps Extension',
    primaerMuskeln: ['trizeps'],
    sekundaerMuskeln: [],
    bewegungsTyp: 'push',
    illustrationId: 'trizepsdruecken',
  },
  {
    id: 'dip_maschine',
    name: 'Dip-Maschine',
    maschine: 'Seated Dip',
    primaerMuskeln: ['trizeps', 'brust'],
    sekundaerMuskeln: ['vordere_schulter'],
    bewegungsTyp: 'push',
    illustrationId: 'dip_maschine',
  },
  {
    id: 'rudermaschine',
    name: 'Rudern sitzend',
    maschine: 'Seated Row',
    primaerMuskeln: ['oberer_ruecken', 'latissimus'],
    sekundaerMuskeln: ['bizeps', 'hintere_schulter'],
    bewegungsTyp: 'pull',
    antagonistGruppe: 'zug_horizontal',
    illustrationId: 'rudermaschine',
  },
  {
    id: 'latzug',
    name: 'Latzug',
    maschine: 'Lat Pulldown',
    primaerMuskeln: ['latissimus'],
    sekundaerMuskeln: ['bizeps', 'oberer_ruecken'],
    bewegungsTyp: 'pull',
    antagonistGruppe: 'zug_vertikal',
    illustrationId: 'latzug',
  },
  {
    id: 'reverse_fly',
    name: 'Reverse Fly',
    maschine: 'Rear Delt Machine',
    primaerMuskeln: ['hintere_schulter', 'oberer_ruecken'],
    sekundaerMuskeln: ['nacken_trapez'],
    bewegungsTyp: 'pull',
    illustrationId: 'reverse_fly',
  },
  {
    id: 'bizepscurls',
    name: 'Bizepscurls',
    maschine: 'Biceps Curl Machine',
    primaerMuskeln: ['bizeps'],
    sekundaerMuskeln: ['unterarme'],
    bewegungsTyp: 'pull',
    illustrationId: 'bizepscurls',
  },
  {
    id: 'beinstrecker',
    name: 'Beinstrecker',
    maschine: 'Leg Extension',
    primaerMuskeln: ['beinstrecker'],
    sekundaerMuskeln: [],
    bewegungsTyp: 'legs_front',
    antagonistGruppe: 'knie_strecker',
    illustrationId: 'beinstrecker',
  },
  {
    id: 'beinpresse',
    name: 'Beinpresse',
    maschine: 'Leg Press',
    primaerMuskeln: ['beinstrecker', 'gesaess'],
    sekundaerMuskeln: ['beinbeuger', 'adduktoren'],
    bewegungsTyp: 'legs_front',
    illustrationId: 'beinpresse',
  },
  {
    id: 'beinbeuger',
    name: 'Beinbeuger',
    maschine: 'Leg Curl',
    primaerMuskeln: ['beinbeuger'],
    sekundaerMuskeln: ['waden'],
    bewegungsTyp: 'legs_back',
    antagonistGruppe: 'knie_beuger',
    illustrationId: 'beinbeuger',
  },
  {
    id: 'wadenheben',
    name: 'Wadenheben',
    maschine: 'Calf Raise',
    primaerMuskeln: ['waden'],
    sekundaerMuskeln: [],
    bewegungsTyp: 'legs_back',
    illustrationId: 'wadenheben',
  },
  {
    id: 'glute_kickback',
    name: 'Glute Kickback',
    maschine: 'Glute Machine',
    primaerMuskeln: ['gesaess'],
    sekundaerMuskeln: ['beinbeuger'],
    bewegungsTyp: 'legs_back',
    illustrationId: 'glute_kickback',
  },
  {
    id: 'abduktoren_maschine',
    name: 'Abduktoren',
    maschine: 'Hip Abduction',
    primaerMuskeln: ['abduktoren'],
    sekundaerMuskeln: ['gesaess'],
    bewegungsTyp: 'legs_back',
    antagonistGruppe: 'abduktion',
    illustrationId: 'abduktoren_maschine',
  },
  {
    id: 'adduktoren_maschine',
    name: 'Adduktoren',
    maschine: 'Hip Adduction',
    primaerMuskeln: ['adduktoren'],
    sekundaerMuskeln: [],
    bewegungsTyp: 'legs_front',
    antagonistGruppe: 'adduktion',
    illustrationId: 'adduktoren_maschine',
  },
  {
    id: 'crunch_maschine',
    name: 'Crunch-Maschine',
    maschine: 'Ab Crunch',
    primaerMuskeln: ['bauch'],
    sekundaerMuskeln: ['hueftbeuger'],
    bewegungsTyp: 'core',
    antagonistGruppe: 'rumpf_bauch',
    illustrationId: 'crunch_maschine',
  },
  {
    id: 'rueckenstrecker_maschine',
    name: 'Rückenstrecker',
    maschine: 'Back Extension',
    primaerMuskeln: ['rueckenstrecker'],
    sekundaerMuskeln: ['gesaess', 'beinbeuger'],
    bewegungsTyp: 'core',
    antagonistGruppe: 'rumpf_ruecken',
    illustrationId: 'rueckenstrecker_maschine',
  },
  {
    id: 'rumpfrotation',
    name: 'Rumpfrotation',
    maschine: 'Rotary Torso',
    primaerMuskeln: ['seitlicher_bauch'],
    sekundaerMuskeln: ['bauch'],
    bewegungsTyp: 'core',
    illustrationId: 'rumpfrotation',
  },
]

// Cardio-Geräte sind ein fester Katalog (kein DB-Store nötig) – die IDs
// entsprechen CardioTypeId und werden ab Phase 5 im WorkoutLog referenziert.
export const CARDIO_GERAETE: CardioGeraet[] = [
  {
    id: 'laufband',
    name: 'Laufband',
    beschreibung:
      'Gehen oder Laufen mit einstellbarer Geschwindigkeit und Steigung. Gut für GA1-Grundlagentraining und 60/120-Intervalle.',
    illustrationId: 'laufband',
  },
  {
    id: 'ergometer',
    name: 'Ergometer (Rad)',
    beschreibung:
      'Fahrradtraining mit einstellbarem Widerstand, gelenkschonend. Geeignet für lange GA1-Einheiten und Intervalle.',
    illustrationId: 'ergometer',
  },
  {
    id: 'crosstrainer',
    name: 'Crosstrainer',
    beschreibung:
      'Ganzkörper-Ausdauertraining mit Arm-Einsatz, geringe Gelenkbelastung. Für GA1 und 60/120-Intervalle geeignet.',
    illustrationId: 'crosstrainer',
  },
]

// 15 Dehnübungen + 8 Blackroll-Übungen (Abschnitt 6, Phase 1)
export const DEHN_UEBUNGEN: StretchExercise[] = [
  {
    id: 'brust_tuerrahmen',
    name: 'Brustdehnung im Türrahmen',
    art: 'dehnen',
    zielMuskeln: ['brust', 'vordere_schulter'],
    anleitung:
      'Unterarm im 90-Grad-Winkel an den Türrahmen legen, einen kleinen Schritt nach vorn machen und den Oberkörper leicht wegdrehen, bis ein Zug in der Brust spürbar ist. Seite wechseln.',
    halteDauerSek: 30,
    illustrationId: 'brust_tuerrahmen',
  },
  {
    id: 'nacken_seitlich',
    name: 'Seitliche Nackendehnung',
    art: 'dehnen',
    zielMuskeln: ['nacken_trapez'],
    anleitung:
      'Aufrecht sitzen, den Kopf langsam zur Seite neigen (Ohr Richtung Schulter). Die gegenüberliegende Schulter aktiv nach unten ziehen. Seite wechseln.',
    halteDauerSek: 30,
    illustrationId: 'nacken_seitlich',
  },
  {
    id: 'hueftbeuger_ausfallschritt',
    name: 'Hüftbeuger im Ausfallschritt',
    art: 'dehnen',
    zielMuskeln: ['hueftbeuger'],
    anleitung:
      'Ausfallschritt, hinteres Knie am Boden. Becken leicht nach hinten kippen (Bauch anspannen) und Hüfte nach vorn schieben, bis es in der Leiste zieht. Seite wechseln.',
    halteDauerSek: 40,
    illustrationId: 'hueftbeuger_ausfallschritt',
  },
  {
    id: 'beinbeuger_stehend',
    name: 'Beinrückseite stehend',
    art: 'dehnen',
    zielMuskeln: ['beinbeuger'],
    anleitung:
      'Ein Bein gestreckt auf eine Erhöhung legen, Rücken gerade halten und mit geradem Oberkörper leicht nach vorn beugen, bis die Beinrückseite zieht. Seite wechseln.',
    halteDauerSek: 40,
    illustrationId: 'beinbeuger_stehend',
  },
  {
    id: 'quadrizeps_stehend',
    name: 'Vorderer Oberschenkel stehend',
    art: 'dehnen',
    zielMuskeln: ['beinstrecker', 'hueftbeuger'],
    anleitung:
      'Im Stand einen Fuß greifen und die Ferse zum Gesäß ziehen. Knie zeigen nach unten zusammen, Becken leicht nach hinten kippen. Seite wechseln.',
    halteDauerSek: 40,
    illustrationId: 'quadrizeps_stehend',
  },
  {
    id: 'waden_wand',
    name: 'Wadendehnung an der Wand',
    art: 'dehnen',
    zielMuskeln: ['waden'],
    anleitung:
      'Hände an die Wand, ein Bein weit nach hinten stellen, Ferse am Boden lassen. Hüfte nach vorn schieben, bis die Wade zieht. Seite wechseln.',
    halteDauerSek: 40,
    illustrationId: 'waden_wand',
  },
  {
    id: 'gesaess_liegend',
    name: 'Gesäßdehnung liegend (Vierer)',
    art: 'dehnen',
    zielMuskeln: ['gesaess', 'abduktoren'],
    anleitung:
      'In Rückenlage einen Knöchel auf das andere Knie legen und das untere Bein mit beiden Händen Richtung Brust ziehen. Seite wechseln.',
    halteDauerSek: 40,
    illustrationId: 'gesaess_liegend',
  },
  {
    id: 'adduktoren_schmetterling',
    name: 'Schmetterlingssitz',
    art: 'dehnen',
    zielMuskeln: ['adduktoren'],
    anleitung:
      'Im Sitzen die Fußsohlen aneinanderlegen, Fersen Richtung Körper ziehen und die Knie mit aufrechtem Rücken sanft Richtung Boden sinken lassen.',
    halteDauerSek: 40,
    illustrationId: 'adduktoren_schmetterling',
  },
  {
    id: 'lat_kniestand',
    name: 'Latissimus im Kniestand',
    art: 'dehnen',
    zielMuskeln: ['latissimus'],
    anleitung:
      'Im Kniestand die Hände weit nach vorn auf den Boden oder eine Erhöhung legen, Brust Richtung Boden sinken lassen und das Gesäß nach hinten schieben.',
    halteDauerSek: 30,
    illustrationId: 'lat_kniestand',
  },
  {
    id: 'schulter_ueberkreuz',
    name: 'Schulter überkreuz',
    art: 'dehnen',
    zielMuskeln: ['hintere_schulter'],
    anleitung:
      'Einen Arm gestreckt vor der Brust überkreuzen und mit dem anderen Arm sanft zum Körper ziehen. Schultern unten lassen. Seite wechseln.',
    halteDauerSek: 30,
    illustrationId: 'schulter_ueberkreuz',
  },
  {
    id: 'trizeps_ueberkopf',
    name: 'Trizeps über Kopf',
    art: 'dehnen',
    zielMuskeln: ['trizeps'],
    anleitung:
      'Einen Arm über den Kopf heben, Ellbogen beugen und die Hand zwischen die Schulterblätter führen. Mit der anderen Hand den Ellbogen sanft nach hinten drücken. Seite wechseln.',
    halteDauerSek: 30,
    illustrationId: 'trizeps_ueberkopf',
  },
  {
    id: 'knie_zur_brust',
    name: 'Knie zur Brust',
    art: 'dehnen',
    zielMuskeln: ['rueckenstrecker', 'gesaess'],
    anleitung:
      'In Rückenlage beide Knie umfassen und sanft zur Brust ziehen. Unteren Rücken bewusst am Boden ablegen und ruhig atmen.',
    halteDauerSek: 40,
    illustrationId: 'knie_zur_brust',
  },
  {
    id: 'bws_rotation',
    name: 'BWS-Rotation im Vierfüßler',
    art: 'dehnen',
    zielMuskeln: ['oberer_ruecken', 'seitlicher_bauch'],
    anleitung:
      'Im Vierfüßlerstand eine Hand hinter den Kopf nehmen, Ellbogen erst zum Boden führen und dann weit nach oben öffnen. Blick folgt dem Ellbogen. Langsam wiederholen, Seite wechseln.',
    halteDauerSek: 30,
    illustrationId: 'bws_rotation',
  },
  {
    id: 'katze_kuh',
    name: 'Katze-Kuh',
    art: 'dehnen',
    zielMuskeln: ['rueckenstrecker', 'bauch'],
    anleitung:
      'Im Vierfüßlerstand den Rücken im Wechsel rund nach oben schieben (Katze) und ins Hohlkreuz absenken (Kuh). Fließend mit der Atmung bewegen.',
    halteDauerSek: 45,
    illustrationId: 'katze_kuh',
  },
  {
    id: 'kindhaltung',
    name: 'Kindhaltung',
    art: 'dehnen',
    zielMuskeln: ['latissimus', 'rueckenstrecker'],
    anleitung:
      'Aus dem Kniestand das Gesäß auf die Fersen setzen, Oberkörper nach vorn ablegen und die Arme weit nach vorn strecken. Ruhig in den Rücken atmen.',
    halteDauerSek: 60,
    illustrationId: 'kindhaltung',
  },
  // Blackroll-Übungen (Faszienrolle)
  {
    id: 'br_bws',
    name: 'Blackroll – Brustwirbelsäule',
    art: 'blackroll',
    zielMuskeln: ['oberer_ruecken'],
    anleitung:
      'Rolle quer unter den oberen Rücken legen, Hände hinter den Kopf, Becken anheben und langsam zwischen Schulterblättern und Rippenbogen hin- und herrollen.',
    halteDauerSek: 60,
    illustrationId: 'br_bws',
  },
  {
    id: 'br_beinbeuger',
    name: 'Blackroll – Beinrückseite',
    art: 'blackroll',
    zielMuskeln: ['beinbeuger'],
    anleitung:
      'Im Sitzen die Rolle unter die Oberschenkelrückseite legen, mit den Händen abstützen und langsam vom Gesäß bis zur Kniekehle rollen. Seite wechseln.',
    halteDauerSek: 60,
    illustrationId: 'br_beinbeuger',
  },
  {
    id: 'br_quadrizeps',
    name: 'Blackroll – Oberschenkel vorn',
    art: 'blackroll',
    zielMuskeln: ['beinstrecker', 'hueftbeuger'],
    anleitung:
      'In Unterarmstützposition die Rolle unter die Oberschenkelvorderseite legen und langsam von der Hüfte bis kurz über das Knie rollen. Seite wechseln.',
    halteDauerSek: 60,
    illustrationId: 'br_quadrizeps',
  },
  {
    id: 'br_waden',
    name: 'Blackroll – Waden',
    art: 'blackroll',
    zielMuskeln: ['waden'],
    anleitung:
      'Im Sitzen die Rolle unter die Wade legen, das andere Bein zur Verstärkung auflegen und langsam von der Achillessehne bis zur Kniekehle rollen. Seite wechseln.',
    halteDauerSek: 60,
    illustrationId: 'br_waden',
  },
  {
    id: 'br_gesaess',
    name: 'Blackroll – Gesäß',
    art: 'blackroll',
    zielMuskeln: ['gesaess'],
    anleitung:
      'Auf die Rolle setzen, einen Knöchel auf das andere Knie legen und das Gewicht auf die Gesäßhälfte des überschlagenen Beins verlagern. Langsam rollen, Seite wechseln.',
    halteDauerSek: 45,
    illustrationId: 'br_gesaess',
  },
  {
    id: 'br_it_band',
    name: 'Blackroll – Oberschenkel seitlich',
    art: 'blackroll',
    zielMuskeln: ['abduktoren'],
    anleitung:
      'In Seitlage die Rolle unter den seitlichen Oberschenkel legen, mit Unterarm und freiem Bein abstützen und langsam zwischen Hüfte und Knie rollen. Seite wechseln.',
    halteDauerSek: 45,
    illustrationId: 'br_it_band',
  },
  {
    id: 'br_lat',
    name: 'Blackroll – Latissimus',
    art: 'blackroll',
    zielMuskeln: ['latissimus'],
    anleitung:
      'In Seitlage den Arm nach oben strecken und die Rolle unter die seitliche Rumpfmuskulatur unterhalb der Achsel legen. Langsam einige Zentimeter auf- und abrollen. Seite wechseln.',
    halteDauerSek: 45,
    illustrationId: 'br_lat',
  },
  {
    id: 'br_fusssohle',
    name: 'Ball – Fußsohle',
    art: 'blackroll',
    zielMuskeln: ['fusssohle'],
    anleitung:
      'Im Stehen einen kleinen Faszienball unter die Fußsohle legen und mit sanftem Druck langsam von der Ferse bis zu den Zehen rollen. Seite wechseln.',
    halteDauerSek: 45,
    illustrationId: 'br_fusssohle',
  },
]
